import { StyleSheet } from 'react-native';
import { designTokens } from './owner-dashboard-styles';

export const professionalStyles = StyleSheet.create({
  // Step Indicator
  stepIndicatorContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 24,
    paddingHorizontal: 16,
    backgroundColor: '#FFFFFF',
    marginBottom: 8,
  },
  stepItem: {
    alignItems: 'center',
  },
  stepCircle: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#F3F4F6',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#E5E7EB',
  },
  stepCircleActive: {
    backgroundColor: designTokens.colors.primary,
    borderColor: designTokens.colors.primary,
    transform: [{ scale: 1.1 }],
  },
  stepCircleCompleted: {
    backgroundColor: designTokens.colors.success,
    borderColor: designTokens.colors.success,
  },
  stepConnector: {
    height: 2,
    width: 32,
    backgroundColor: '#E5E7EB',
    marginHorizontal: 8,
  },
  stepConnectorActive: {
    backgroundColor: designTokens.colors.primary,
  },
  stepTextContainer: {
    marginTop: 8,
    alignItems: 'center',
    maxWidth: 120,
  },
  stepTitle: {
    fontSize: 12,
    fontWeight: '600',
    color: '#111827',
    textAlign: 'center',
  },
  stepSubtitle: {
    fontSize: 10,
    color: '#6B7280',
    textAlign: 'center',
  },

  // Professional Inputs - Modern Design
  inputGroup: {
    marginBottom: 28,
    marginTop: 0,
  },
  inputLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#1F2937',
    marginBottom: 12,
    letterSpacing: 0.1,
  },
  inputContainer: {
    position: 'relative',
  },
  inputIcon: {
    position: 'absolute',
    left: 16,
    top: 14,
    zIndex: 1,
  },
  input: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#D1D5DB',
    borderRadius: 10,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 15,
    color: '#111827',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.03,
    shadowRadius: 3,
    elevation: 1,
  },
  inputError: {
    borderColor: '#F87171',
    backgroundColor: '#FEF2F2',
    borderWidth: 1.5,
  },
  errorText: {
    fontSize: 12,
    color: '#DC2626',
    marginTop: 8,
    fontWeight: '500',
    lineHeight: 16,
  },
  warningBanner: {
    backgroundColor: '#FEF2F2',
    borderWidth: 1,
    borderColor: '#EF4444',
    borderRadius: 12,
    padding: 16,
    marginBottom: 20,
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  inputWithIcon: {
    paddingLeft: 48,
  },
  inputMultiline: {
    height: 100,
    textAlignVertical: 'top',
  },
  inputHelper: {
    fontSize: 12,
    color: '#6B7280',
    marginTop: 6,
    marginBottom: 4,
    lineHeight: 16,
  },

  // Option Cards - Modern & Professional Design
  optionsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 0,
    marginTop: 0,
    justifyContent: 'center',
    alignItems: 'center',
  },
  optionCard: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#E5E7EB',
    borderRadius: 10,
    paddingHorizontal: 16,
    paddingVertical: 12,
    flex: 1,
    minWidth: '30%',
    maxWidth: '48%',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 2,
    elevation: 1,
  },
  optionCardError: {
    borderColor: '#FCA5A5',
    backgroundColor: '#FEF2F2',
    borderWidth: 1.5,
  },
  optionCardActive: {
    backgroundColor: '#F0F9FF',
    borderColor: designTokens.colors.primary,
    borderWidth: 2,
    shadowColor: designTokens.colors.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 4,
    elevation: 3,
  },
  optionText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#4B5563',
    textAlign: 'center',
    lineHeight: 20,
    letterSpacing: 0.1,
  },
  optionTextActive: {
    color: designTokens.colors.primary,
    fontWeight: '600',
  },

  // Availability Status - Original Design (Gray Background)
  availabilityOptionCard: {
    backgroundColor: '#F9FAFB',
    borderWidth: 1.5,
    borderColor: '#E5E7EB',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    flex: 1,
    minWidth: '30%',
    maxWidth: '30%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  availabilityOptionCardActive: {
    backgroundColor: '#EEF2FF',
    borderColor: designTokens.colors.primary,
    borderWidth: 2,
    shadowColor: designTokens.colors.primary,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 3,
    elevation: 2,
  },
  availabilityOptionText: {
    fontSize: 13,
    fontWeight: '500',
    color: '#6B7280',
    textAlign: 'center',
    lineHeight: 18,
  },
  availabilityOptionTextActive: {
    color: designTokens.colors.primary,
    fontWeight: '700',
  },

  // Amenities - Original Design (Gray Background)
  amenityOptionCard: {
    backgroundColor: '#F9FAFB',
    borderWidth: 1.5,
    borderColor: '#E5E7EB',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    flex: 1,
    minWidth: '30%',
    maxWidth: '48%',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 36,
  },
  amenityOptionCardActive: {
    backgroundColor: '#EEF2FF',
    borderColor: designTokens.colors.primary,
    borderWidth: 2,
    shadowColor: designTokens.colors.primary,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 3,
    elevation: 2,
  },
  amenityOptionText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#6B7280',
    textAlign: 'center',
    lineHeight: 16,
    flexWrap: 'wrap',
    flexShrink: 1,
    width: '100%',
    alignSelf: 'center',
  },
  amenityOptionTextActive: {
    color: designTokens.colors.primary,
    fontWeight: '600',
  },

  // Property Type - Modern Card Design
  propertyTypeCard: {
    backgroundColor: '#FFFFFF',
    borderWidth: 2,
    borderColor: '#E5E7EB',
    borderRadius: 12,
    paddingHorizontal: 20,
    paddingVertical: 16,
    flex: 1,
    minWidth: '30%',
    maxWidth: '48%',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  // Property Type - Horizontal Scrollable Design
  propertyTypeScrollContainer: {
    marginTop: 8,
    marginBottom: 16,
  },
  propertyTypeScrollContent: {
    paddingHorizontal: 4,
    paddingVertical: 4,
  },
  propertyTypeScrollCard: {
    backgroundColor: '#FFFFFF',
    borderWidth: 2,
    borderColor: '#E5E7EB',
    borderRadius: 16,
    paddingHorizontal: 24,
    paddingVertical: 18,
    minWidth: 140,
    width: 140,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 3,
    marginHorizontal: 6,
  },
  propertyTypeScrollCardActive: {
    backgroundColor: '#F0FDF4',
    borderColor: designTokens.colors.primary,
    borderWidth: 2.5,
    shadowColor: designTokens.colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 10,
    elevation: 5,
  },
  propertyTypeScrollText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#374151',
    textAlign: 'center',
    lineHeight: 22,
    letterSpacing: 0.3,
  },
  propertyTypeScrollTextActive: {
    color: designTokens.colors.primary,
    fontWeight: '700',
    fontSize: 16,
  },
  propertyOptionCardError: {
    borderColor: '#FCA5A5',
    backgroundColor: '#FEF2F2',
    borderWidth: 2,
  },
  propertyTypeCardActive: {
    backgroundColor: '#F0FDF4',
    borderColor: designTokens.colors.primary,
    borderWidth: 2.5,
    shadowColor: designTokens.colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 4,
  },
  propertyTypeText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#374151',
    textAlign: 'center',
    lineHeight: 20,
    letterSpacing: 0.2,
  },
  propertyTypeTextActive: {
    color: designTokens.colors.primary,
    fontWeight: '700',
    fontSize: 15,
  },
  
  // Property Type & Rental Type - Original Design (Gray Background) - Kept for backward compatibility
  propertyOptionCard: {
    backgroundColor: '#F9FAFB',
    borderWidth: 1.5,
    borderColor: '#E5E7EB',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    flex: 1,
    minWidth: '30%',
    maxWidth: '30%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  propertyOptionCardActive: {
    backgroundColor: '#EEF2FF',
    borderColor: designTokens.colors.primary,
    borderWidth: 2,
    shadowColor: designTokens.colors.primary,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 3,
    elevation: 2,
  },
  propertyOptionText: {
    fontSize: 13,
    fontWeight: '500',
    color: '#6B7280',
    textAlign: 'center',
    lineHeight: 18,
  },
  propertyOptionTextActive: {
    color: designTokens.colors.primary,
    fontWeight: '700',
  },

  // Checkboxes
  checkbox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F9FAFB',
    borderWidth: 2,
    borderColor: '#E5E7EB',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    marginBottom: 10,
  },
  checkboxActive: {
    backgroundColor: '#EEF2FF',
    borderColor: designTokens.colors.primary,
  },
  checkboxBox: {
    width: 24,
    height: 24,
    borderRadius: 6,
    backgroundColor: '#FFFFFF',
    borderWidth: 2,
    borderColor: '#D1D5DB',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  checkboxBoxActive: {
    backgroundColor: designTokens.colors.primary,
    borderColor: designTokens.colors.primary,
  },
  checkboxLabel: {
    fontSize: 14,
    color: '#374151',
    flex: 1,
  },
  checkboxLabelActive: {
    color: '#111827',
    fontWeight: '500',
  },

  // Section Headers - Modern Design
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 28,
    paddingBottom: 18,
    borderBottomWidth: 1.5,
    borderBottomColor: '#E5E7EB',
  },
  sectionIcon: {
    width: 42,
    height: 42,
    borderRadius: 12,
    backgroundColor: '#F0F9FF',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 14,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#111827',
    flex: 1,
    letterSpacing: 0.2,
  },

  // Professional Header
  professionalHeader: {
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 24,
    paddingVertical: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#F3F4F6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitleContainer: {
    flex: 1,
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#111827',
  },
  headerSubtitle: {
    fontSize: 14,
    color: '#6B7280',
    marginTop: 2,
  },

  // Progress Display
  progressContainer: {
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 24,
    paddingVertical: 16,
  },
  progressInfo: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  progressText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#374151',
  },
  progressBar: {
    height: 8,
    backgroundColor: '#E5E7EB',
    borderRadius: 4,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    backgroundColor: designTokens.colors.primary,
    borderRadius: 4,
  },

  // Payment Warning Banner
  paymentWarningBanner: {
    backgroundColor: '#FEF3C7',
    borderBottomWidth: 1,
    borderBottomColor: '#FCD34D',
    paddingHorizontal: 20,
    paddingVertical: 16,
  },
  paymentWarningContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  paymentWarningTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#92400E',
    marginBottom: 4,
  },
  paymentWarningText: {
    fontSize: 13,
    color: '#78350F',
    lineHeight: 18,
  },
  paymentWarningButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F59E0B',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 8,
    gap: 6,
    shadowColor: '#F59E0B',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 2,
  },
  paymentWarningButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
  },

  // Professional Footer
  professionalFooter: {
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 24,
    paddingVertical: 16,
    flexDirection: 'row',
    gap: 12,
    borderTopWidth: 1,
    borderTopColor: '#E5E7EB',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 4,
  },
  footerButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 16,
    borderRadius: 12,
    gap: 8,
  },
  footerButtonPrimary: {
    backgroundColor: designTokens.colors.primary,
  },
  footerButtonSecondary: {
    backgroundColor: '#F3F4F6',
  },
  footerButtonSuccess: {
    backgroundColor: designTokens.colors.success,
  },
  footerButtonText: {
    fontSize: 15,
    fontWeight: '600',
  },
  footerButtonTextPrimary: {
    color: '#FFFFFF',
  },
  footerButtonTextSecondary: {
    color: '#374151',
  },

  // Content Area - Modern Design
  stepContent: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 24,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
    borderWidth: 1,
    borderColor: '#F3F4F6',
  },

  // Media Upload
  uploadCard: {
    backgroundColor: '#F9FAFB',
    borderWidth: 2,
    borderColor: '#E5E7EB',
    borderStyle: 'dashed',
    borderRadius: 12,
    padding: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  uploadIcon: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: '#EEF2FF',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  uploadTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#111827',
    marginBottom: 8,
  },
  uploadSubtitle: {
    fontSize: 14,
    color: '#6B7280',
    textAlign: 'center',
  },

  // Photo Grid
  photoGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginTop: 12,
  },
  photoCard: {
    width: 110,
    height: 110,
    borderRadius: 12,
    overflow: 'hidden',
    position: 'relative',
  },
  photoImage: {
    width: '100%',
    height: '100%',
  },
  photoRemoveButton: {
    position: 'absolute',
    top: 8,
    right: 8,
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: 'rgba(239, 68, 68, 0.9)',
    alignItems: 'center',
    justifyContent: 'center',
  },

  // Rule Item Styles
  ruleItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#F9FAFB',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  ruleText: {
    flex: 1,
    fontSize: 14,
    color: '#374151',
    fontWeight: '500',
  },
  ruleRemoveButton: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#FEE2E2',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 8,
  },
});

